"""consolidated final schema

Revision ID: 9630f187f32f
Revises: 
Create Date: 2026-03-18 20:41:13.987569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9630f187f32f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_algo', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("hash_algo IN ('sha256')", name='ck_duplicate_groups_hash_algo_allowed'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_algo', 'content_hash', name='uq_duplicate_groups_hash_algo_content_hash')
    )
    op.create_index('ix_duplicate_groups_hash_lookup', 'duplicate_groups', ['hash_algo', 'content_hash'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=False),
    sa.Column('hash_algo', sa.String(length=16), server_default='sha256', nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', 'deleting', 'deleted', name='doc_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}' ::jsonb"), nullable=True),
    sa.Column('declared_langs', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}' ::text[]"), nullable=True),
    sa.Column('detected_langs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}' ::jsonb"), nullable=True),
    sa.Column('primary_lang', sa.String(), nullable=True),
    sa.Column('primary_script', sa.String(), nullable=True),
    sa.Column('sourcetype', sa.String(), nullable=True),
    sa.CheckConstraint("hash_algo IN ('sha256')", name='ck_documents_hash_algo_allowed'),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_duplicate_group_id'), 'documents', ['duplicate_group_id'], unique=False)
    op.create_index('ix_documents_hash_lookup', 'documents', ['hash_algo', 'content_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index('ix_documents_status_created', 'documents', ['status', 'created_at'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_document_id', 'entities', ['document_id'], unique=False)
    op.create_index('ix_entities_label', 'entities', ['label'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"events": []}\'::jsonb'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_document_id', 'jobs', ['document_id'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('lang_probs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('primary_lang', sa.String(), nullable=True),
    sa.Column('primary_script', sa.String(), nullable=True),
    sa.Column('sourcetype', sa.String(), nullable=True),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}' ::jsonb"), nullable=True),
    sa.Column('text_layer', sa.Text(), nullable=True),
    sa.Column('md_uri', sa.String(), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_pages_document_id_index')
    )
    op.create_index(op.f('ix_pages_document_id'), 'pages', ['document_id'], unique=False)
    op.create_index('ix_pages_markdown_fts', 'pages', [sa.literal_column("to_tsvector('simple', coalesce(markdown, ''))")], unique=False, postgresql_using='gin')
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'filename', name='uq_page_images_page_id_filename')
    )
    op.create_index(op.f('ix_images_page_id'), 'images', ['page_id'], unique=False)
    op.create_index('ix_page_images_filename', 'images', ['filename'], unique=False)
    op.create_index('ix_page_images_page_id', 'images', ['page_id'], unique=False)
    op.create_table('page_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('bbox_px', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'block_index', name='uq_page_blocks_page_id_block_index')
    )
    op.create_index('ix_page_blocks_page_id', 'page_blocks', ['page_id'], unique=False)
    op.create_index('ix_page_blocks_page_id_category', 'page_blocks', ['page_id', 'category'], unique=False)
    op.create_index('ix_page_blocks_text_fts', 'page_blocks', [sa.literal_column("to_tsvector('simple', coalesce(text, ''))")], unique=False, postgresql_using='gin')
    op.create_table('page_mt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('translated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'lang', name='uq_page_mt_page_id_lang')
    )
    op.create_index(op.f('ix_page_mt_page_id'), 'page_mt', ['page_id'], unique=False)
    op.create_index('ix_page_mt_text_fts', 'page_mt', [sa.literal_column("to_tsvector('simple', coalesce(text, ''))")], unique=False, postgresql_using='gin')
    op.create_table('block_mt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('translated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['page_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'lang', name='uq_block_mt_block_id_lang')
    )
    op.create_index(op.f('ix_block_mt_block_id'), 'block_mt', ['block_id'], unique=False)
    op.create_index('ix_block_mt_text_fts', 'block_mt', [sa.literal_column("to_tsvector('simple', coalesce(text, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_mt_text_fts', table_name='block_mt', postgresql_using='gin')
    op.drop_index(op.f('ix_block_mt_block_id'), table_name='block_mt')
    op.drop_table('block_mt')
    op.drop_index('ix_page_mt_text_fts', table_name='page_mt', postgresql_using='gin')
    op.drop_index(op.f('ix_page_mt_page_id'), table_name='page_mt')
    op.drop_table('page_mt')
    op.drop_index('ix_page_blocks_text_fts', table_name='page_blocks', postgresql_using='gin')
    op.drop_index('ix_page_blocks_page_id_category', table_name='page_blocks')
    op.drop_index('ix_page_blocks_page_id', table_name='page_blocks')
    op.drop_table('page_blocks')
    op.drop_index('ix_page_images_page_id', table_name='images')
    op.drop_index('ix_page_images_filename', table_name='images')
    op.drop_index(op.f('ix_images_page_id'), table_name='images')
    op.drop_table('images')
    op.drop_index('ix_pages_markdown_fts', table_name='pages', postgresql_using='gin')
    op.drop_index(op.f('ix_pages_document_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_document_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_entities_label', table_name='entities')
    op.drop_index('ix_entities_document_id', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_documents_status_created', table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index('ix_documents_hash_lookup', table_name='documents')
    op.drop_index(op.f('ix_documents_duplicate_group_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_duplicate_groups_hash_lookup', table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    # ### end Alembic commands ###
